let lessons = [
    {
        id:1001,
        title:"Art Tuition",
        description:"Art tuition after school hours to get improve the students skills",
        price:2000,
        image:"images/art.png",
        availableInventory:10,
        space:10,
        location:"Dubai",
        rating:3,
        },
    {
        id:1002,
        title:"Biology Tuition",
        description:"Biology tuition after school hours to get improve the students skills",
        price:1000,
        image:"images/biology.png",
        availableInventory:10,
        space:10,
        location: "Ras Al Khaimah",
        rating:2,
    },
    {
        id:1003,
        title:"Chemistry Tuition ",
        description:"Chemistry tuition after school hours to get improve the students skills",
        price:3000,
        image:"images/Chemistry.png",
        availableInventory:10,
        space:10,
        location: "Dubai",
        rating:5,
    },
    {
        id:1004,
        title:"Computer Science Tuition",
        description:"Computer Science tuition after school hours to get improve the students skills",
        price:4000,
        image:"images/cs.png",
        availableInventory:10,
        space:10,
        location: "Abu Dhabi",
        rating:1,
    },        
    {
        id:1005,
        title:"English Tuition",
        description:"English tuition after school hours to get improve the students skills",
        price:5000,
        image:"images/english.png",
        availableInventory:10,
        space:10,
        location: "Al Ain",
        rating:4,
    },
    {
        id:1006,
        title:"Geography Tuition",
        description:"Geography tuition after school hours to get improve the students skills",
        price:1490,
        image:"images/geography.png",
        availableInventory:10,
        space:10,
        location: "Fujairah",
        rating:3,
        },
    {
        id:1007,
        title:"History Tuition",
        description:"History tuition after school hours to get improve the students skills",
        price:3200,
        image:"images/history.png",
        availableInventory:10,
        space:10,
        location: "Ajman",
        rating:2,
    },
    {
        id:1008,
        title:"Math Tuition ",
        description:"Math tuition after school hours to get improve the students skills",
        price:6500,
        image:"images/math.png",
        availableInventory:10,
        space:10,
        location: "Sharjah",
        rating:5,
    },
    {
        id:1004,
        title:"Physics Tuition",
        description:"Physics tuition after school hours to get improve the students skills",
        price:5500,
        image:"images/physics.png",
        availableInventory:10,
        space:10,
        location: "Umm Al Quwain",
        rating:1,
    },        
    {
        id:1010,
        title:"Psychology Tuition",
        description:"Psychology tuition after school hours to get improve the students skills",
        price:1200,
        image:"images/psychology.png",
        availableInventory:10,
        space:10,
        location: "Dubai",
        rating:4,
    }
]